<?php
$session = new Session();
$user_controller = new UserController();

$permamount = 1;

if ($session->exists('username')) {
    $user = $user_controller->getByUsername($_SESSION['username']);
    $permamount = $user->getGebruikerRechtgroep();
} else {
}

if ($permamount == "2") {
    $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD', 'CAN_SHOW_STUDENTOVERVIEW', 'CAN_SHOW_PROGRESS', 'CAN_EDIT_PROGRESS', 'CAN_SHOW_PROGRESS', 'CAN_CREATE_PROGRESS', 'CAN_EDIT_PROGRESS');
} else if ($permamount == "3") {
    $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD', 'CAN_SHOW_STUDENTOVERVIEW', 'CAN_SHOW_PROGRESS', 'CAN_SHOW_PROGRESS', 'CAN_CREATE_PROGRESS', 'CAN_EDIT_PROGRESS');
} else if ($permamount == "4") {
    $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD', 'CAN_SHOW_STUDENTOVERVIEW', 'CAN_SHOW_PROGRESS', 'CAN_EDIT_PROGRESS', 'CAN_SHOW_PROGRESS', 'CAN_CREATE_PROGRESS', 'CAN_EDIT_PROGRESS');
} else if ($permamount == "5") {
    $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD', 'CAN_SHOW_USER', 'CAN_SHOW_CURSUS', 'CAN_SHOW_LOCATION',
        'CAN_SHOW_EDUCATION', 'CAN_SHOW_EDUCATIONBLOCK', 'CAN_EDIT_LOCATION', 'CAN_SHOW_STUDENTOVERVIEW', 'CAN_SHOW_PROGRESS', 'CAN_CREATE_PROGRESS', 'CAN_EDIT_PROGRESS', 'CAN_CREATE_CURSUS', 'CAN_EDIT_CURSUS', 'CAN_CREATE_CURSUSBLOCK', 'CAN_CREATE_USER', 'CAN_CREATE_LOCATION', 'CAN_CREATE_EDUCATION', 'CAN_CREATE_EDUCATIONBLOCK', 'CAN_EDIT_EDUCATIONBLOCK', 'CAN_EDIT_EDUCATION', 'CAN_EDIT_USER', 'CAN_CONNECT_EDUCATION');
} else {
    $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD');
}

?>
